# Site settings
title: Data Science for High-Throughput Sequencing
email: dntse@stanford.edu
description: "Course materials and notes for Stanford class EE 372: Data Science for High-Throughput Sequencing."
baseurl: ""
url: "http://data-science-sequencing.github.io"
github_username:  data-science-sequencing
# Build settings
gems:
  - jekyll-pandoc
markdown: pandoc
permalink: pretty
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    # - csl: _styles/apa.csl
    # - bibliography: bibliography/references.bib
