# Site settings
title: Data Science for High-Throughput Sequencing
email: gkamath@stanford.edu,jessez@stanford.edu,dntse@stanford.edu
email_string:  "&#123 gkamath, jessez, dntse &#125  @stanford.edu"
description: "Course materials and notes for Stanford class EE 372: Data Science for High-Throughput Sequencing."
baseurl: ""
url: "http://data-science-sequencing.github.io"
github_username:  data-science-sequencing
# Build settings
markdown: kramdown
permalink: pretty
